# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/andrius/.local/bin/UnrealEngine5
GAMEPROJECTFILE =/home/andrius/Projektai/Games/RoomPlanner01/RoomPlanner01.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	RoomPlanner01-Linux-DebugGame  \
	RoomPlanner01-Linux-Shipping  \
	RoomPlanner01 \
	RoomPlanner01Editor-Linux-DebugGame  \
	RoomPlanner01Editor-Linux-Shipping  \
	RoomPlanner01Editor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RoomPlanner01Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RoomPlanner01Editor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

RoomPlanner01-Linux-DebugGame:
	 $(PROJECTBUILD) RoomPlanner01 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RoomPlanner01-Linux-Shipping:
	 $(PROJECTBUILD) RoomPlanner01 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RoomPlanner01:
	 $(PROJECTBUILD) RoomPlanner01 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

RoomPlanner01Editor-Linux-DebugGame:
	 $(PROJECTBUILD) RoomPlanner01Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RoomPlanner01Editor-Linux-Shipping:
	 $(PROJECTBUILD) RoomPlanner01Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RoomPlanner01Editor:
	 $(PROJECTBUILD) RoomPlanner01Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
